include('shared.lua')

language.Add("sent_killicon_hgrunt", "Human Grunt")
language.Add("sent_killicon_barney", "Barney")
language.Add("sent_killicon_hwgrunt", "Heavy Grunt")
language.Add("sent_killicon_sentry", "Sentry")
language.Add("sent_killicon_hassassin", "Human Assassin")
language.Add("sent_killicon_archer", "Archer")

killicon.Add( "sent_killicon_agrunt", "HUD/killicons/agrunt",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_houndeye", "HUD/killicons/houndeye",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_bullchicken", "HUD/killicons/bullsquid",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_hgrunt", "HUD/killicons/hgrunt",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_hwgrunt", "HUD/killicons/monster_hwgrunt",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_sentry", "HUD/killicons/monster_sentry",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_islave", "HUD/killicons/aslave",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_archer", "HUD/killicons/monster_archer",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_babycrab", "HUD/killicons/babycrab",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_bigmomma", "HUD/killicons/gonarch",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_gargantua", "HUD/killicons/gargantua",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_headcrab", "HUD/killicons/headcrab",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_hassassin", "HUD/killicons/monster_human_assassin",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_ichthyosaur", "HUD/killicons/monster_ichthyosaur",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_panthereye", "HUD/killicons/panthereye",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_parasite", "HUD/killicons/monster_parasite",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_sentry", "HUD/killicons/monster_sentry",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_snark", "HUD/killicons/snark",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_zombie", "HUD/killicons/zombie",Color ( 255, 80, 0, 255 ) )
killicon.Add( "sent_killicon_hassassin","HUD/killicons/monster_human_assassin",Color ( 255, 80, 0, 255 ) )

function ENT:Draw()
	self.Entity:DrawModel()
end 
