list.Set( "NPCWeapons", "weapon_snark", "Snark" )
list.Set( "NPCWeapons", "weapon_hornetgun", "Hornet Gun" )
list.Set( "NPCWeapons", "weapon_9mmhandgun", "9mm Handgun" )
list.Set( "NPCWeapons", "weapon_9mmAR", "MP5" )
list.Set( "NPCWeapons", "weapon_gauss", "Gauss cannon" )
//list.Set( "NPCWeapons", "weapon_egon", "Egon" )
list.Set( "NPCWeapons", "weapon_handgrenade", "Handgrenade" )